"""INSTR_GENERATED_LOADED: a heavy generated file loaded in every session."""

from __future__ import annotations

HEAD = "# Registry\n\n> Auto-generated by scripts/build.py. Do not edit manually.\n\n"


def _repo(tmp_path, agents_text, claude="@AGENTS.md\n\nShort project notes.\n"):
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "CLAUDE.md").write_text(claude)
    (repo / "AGENTS.md").write_text(agents_text)
    return repo


def _budget(m, repo, tmp_path, monkeypatch, user=False):
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(tmp_path / "cfg"))
    (tmp_path / "cfg").mkdir(exist_ok=True)
    rep = m.Report()
    m.token_budget(repo, user, m.load_policy(None, [repo]), rep)
    return [f for f in rep.findings if f.code == "INSTR_GENERATED_LOADED"]


def test_heavy_generated_file_is_reported(linter_module, tmp_path, monkeypatch):
    repo = _repo(tmp_path, HEAD + "- agent entry line\n" * 1200)
    found = _budget(linter_module, repo, tmp_path, monkeypatch)
    assert len(found) == 1
    assert found[0].level == "info"
    assert "AGENTS.md" in found[0].message
    assert "do not import it" in found[0].message


def test_small_generated_file_is_ignored(linter_module, tmp_path, monkeypatch):
    repo = _repo(tmp_path, HEAD + "- one line\n" * 20)
    assert _budget(linter_module, repo, tmp_path, monkeypatch) == []


def test_heavy_handwritten_file_is_not_called_generated(linter_module, tmp_path, monkeypatch):
    repo = _repo(tmp_path, "# Notes written by hand\n\n" + "- a rule that someone wrote\n" * 1200)
    assert _budget(linter_module, repo, tmp_path, monkeypatch) == []


def test_marker_must_be_near_the_top(linter_module, tmp_path, monkeypatch):
    body = "# Notes\n\n" + "- a rule\n" * 1200 + "\nThis was generated by a tool at the very end.\n"
    repo = _repo(tmp_path, body)
    assert _budget(linter_module, repo, tmp_path, monkeypatch) == []


def test_user_scope_file_is_not_repeated_in_every_project(linter_module, tmp_path, monkeypatch):
    repo = tmp_path / "repo"
    repo.mkdir()
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(tmp_path / "cfg"))
    cfg = tmp_path / "cfg"
    cfg.mkdir()
    (cfg / "CLAUDE.md").write_text(HEAD + "- entry line\n" * 1500)
    m = linter_module
    rep = m.Report()
    m.token_budget(repo, False, m.load_policy(None, [repo]), rep)
    assert [f for f in rep.findings if f.code == "INSTR_GENERATED_LOADED"] == []
    rep = m.Report()
    m.token_budget(repo, True, m.load_policy(None, [repo]), rep)
    assert len([f for f in rep.findings if f.code == "INSTR_GENERATED_LOADED"]) == 1
